spring:
  application: 
    name: api-gateway
    
    
zuul:
  routes:
    ride:
      path: /rides/**
      service-Id: ride
      stripPrefix: false
    driver-inventory:
      path: /drivers/**
      service-Id: driver-inventory
      stripPrefix: false
 
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  
hystrix:
  command:
    myusers-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
     
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/
    
server: 
  port: 8081